README.md
Demo code had run-on generation until the declaration of the eos token
=> Added the EOS token in the demo code to prevent run-on generation

demo/README.md, finetune/README.md
Minor spelling and grammar fixes.
=> Improved English README

README.md, quantization/awq/README.md, quantization/awq/eval_quantized_model.py, quantization/awq/quant_autoawq.py, quantization/gptq/README.md, quantization/gptq/eval_quantized_model.py, quantization/gptq/quant_autogptq.py, requirements.txt
The PR adds gptq and awq quantization demos to Yi models. Note that Yi models' support is newly added to AutoAWQ, one must build it from the source for now.
=> Add quantization scripts

README.md
=> update the instructions for installing a local environment in the readme

README.md
Fix micromamba installation url in README.md
=> Fix micromamba installation url in README.md

README.md
=> Add instruction on how to create prompt

README.md
=> [doc][feat] add model explanations

docs/yi_llama.cpp.md
This is a follow-up for https://github.com/01-ai/Yi/pull/284
The preview looks good:
=> [doc][improve] change relative path to absolute path

finetune/README.md, finetune/README_CN.md
=> [doc][improve] Remove non-existent files from file preview of latest Yi Model

README.md, docs/learning_hub.md
LlamaEdge provides a strong alternative to Python in AI inference. LlamaEdge can run Yi-34B-Chat everywhere at full hardware acceleration without any change to the binary code.
=> Add LlamaEdge

VL/README.md, VL/cli.py
Allows users to conversate with the model similar to the Gradio web interface but via CLI.
=> added a command line interface for Yi-VL model

README_CN.md
=> [doc][feat] modified readme_CN.

README.md
Modified the html code of "back to top".
typo
=> [doc][feat] modified readme

README.md, README_CN.md
Hello maintainer 👋
Happy New Year, submit a VL related user experience, hope it helps
thank you
=> docs: add yi-vl user experience

README.md, README_CN.md
- Changed "llama" and "LLaMA" to "Llama".
- Made some punctuation corrections.
- Optimized the Learning Hub's structure (both in readme and readme_CN).
=> [doc][feat]modified readme and readme_CN

README.md, README_CN.md
=> [doc][feat] modified readme and readme_CN.

README.md, README_CN.md
=> [doc][feat] modified readme and readme_CN (add new technical content).

.github/workflows/build_docker_image.yml
=> annotate domestic image deployment

VL/openai_api.py
=> Feat fix openai vl bug

VL/openai_api.py
=> fix cache not cleared bug

HUGGINGFACE_README.md, LICENSE, MODEL_LICENSE_AGREEMENT.txt, README.md, README/huggingface_header.md, README/modelscope_header.md, README/wisemodel_header.md, README_CN.md
=> update license to apache-2.0

README_CN.md
update license description CN version
=> update license description CN version

README_CN.md
modify license description CN version according to writing norms
=> modify according to writing norms

NOTICE, README.md
add a notice file
add license information in readme.md
=> [NOTICE File](add to the repo)
